import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/util/provider/theme";
import Footer from "@/layout/footer";
import { Toaster } from "react-hot-toast";
import { ReactQueryClientProvider } from "@/util/provider/react-query";
import AuthRedirect from "@/util/provider/authenticated";
import NextAuthProvider from "@/util/provider/next-auth";
import { getServerSession } from "next-auth";
import { options } from "@/lib/db/auth";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <AuthRedirect>
          <ReactQueryClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <body className={plusJakartaSans.className}>
                {children}
                <Footer />
              </body>
            </ThemeProvider>
            <Toaster position="bottom-right" reverseOrder={false} />
          </ReactQueryClientProvider>
        </AuthRedirect>
      </NextAuthProvider>
    </html>
  );
}
